# Truth, Dare and Spill strings

TRUTH_MSG = ["Lebih suka mendem perasaan atau confess langsung?",
              "Paling bisa masak apa?",
              "Nama temen paling unik",
              "Pilih sayuran atau ikan?",
              "Jadi super pinter/super rajin?",
              "Kalo lu suka sama orang, lu diem/ngaku?",
              "Tempat tinggal impian",
              "Sebutin kenangan teralay",
              "Sehari mandi berapa kali?",
              "Pernah pingsan?",
              "Sebutkan 5 kekurangan lu!",
              "Kalo lu lagi sedih banget, lu bakal ngapain?",
              "Pernah ditinggal karna alasan ga jelas?",
              "Lebih suka baca novel/komik?",
              "Pernah mimisan?",
              "Suka ngerasa cape ga sama hidup?",
              "Hewan yang paling di benci?",
              "Pekerjaan impian?",
              "Pernah kesurupan?",
              "Lebih pengen punya abang/kakak/adek?",
              "Tipe pasangan idaman",
              "Pernah pake baju kebalik?",
              "Mimpi teraneh yg pernah lu pikirkan?",
              "Bisa renang ga?",
              "Kalo kamu di kasih 3 permintaan, apa yang akan kamu minta?",
              "Pernah gak, lupa cebok?",
              "Foto nilai raport pas sd, trus kirim ke sini",
              "Lebih suka sayur apa?",
              "Lu pernah gamon ga?",
              "Lu pernah ga ngupil terus di makan?",
              "Lu kalo tidur pernah mimpi setan ga?",
              "Lu pernah tidur di lemari?",
              "Pernah nyuri uang ortu?"
             ]


DARE_MSG = ["Chat temen pake capslock tiba tiba",
             "Cium orang sebelah",
             "SS search Instagram",
             "SS search Google",
             "VN ngomong bebas pake bahasa daerah",
             "SS chat sama ortu",
             "Chat orang yg lu suka dan nyatakan perasaanmu!",
             "SS history call wa",
             "Nyanyi dangdut keras keras",
             "Kirim foto pake filter aneh",
             "Ss chat wa terakhir",
             "Kirim foto terakhir di galeri",
             "Satir selama 24 jam",
             "Bilang ke pacarmu 'kita putus' dan tunggu tanggapannya",
             "Bucin ke salah satu anggota grup (no gay/lesbi)",
             "Kasih kata 'nyot' setiap ngetik di pc/gc selama 2 jam",
             "Nama orang yang pernah bikin lo naksir",
             "Tag orang yg lu taksir di grup ini (kalo gk ada skip kasian jones)",
             "Chat mantan dengan kata 'hi mantan, apa kabar?'",
             "Screenshot chat tergajebo sama temen/doi lo",
             "Kirim foto masa kecil",
             "Bikin story foto aib",
             "SS lockscreen",
             "Teriak-teriak gajelas di luar rumahmu",
             "ss alarm",
             "Kirim aib ke mama/papa",
             "Keluar dari grup sekolah",
             "Bilang i love you ke guru mtk",
             "Gofoodin temen jajan termurah",
             "Tunjukkin foto lu di rapor sd",
             "24 jam nge jamet",
             "24 jam no toxic",
             "24 jam harus toxic!",
             "Off tele selama 24 jam",
             "Bilang ke salah satu gurumu 'Aku capek belajar sama bapak/ibu'",
             "Buat story wa jamet+alay"
            ]


SPILL_MSG = ["Spill terakhir kali chat sama doi!",
              "Spill inisial gebetan",
              "Spill warna rambut yang pengen dicoba",
              "Spill foto bareng mantan/ crush",
              "Spill tempat favorite pas lagi galau",
              "Spill lagu favorite pas lagi galau",
              "Spill tipe crushmu",
              "Spill Pernah selfharming?",
              "Spill orang yang jomblo abadi",
              "Spill orang yang selalu nyemangatin lu",
              "Spill pengagum rahasia",
              "Spill yg pernah jadi TTM lu",
              "Spill yang sering dicuekin pacarnya",
              "Spill mapel apa yang nilainya paling jelek di rapor selama sekolah, sebutin nilainya!",
              "Spill yang paling gila di grup ini",
              "Spill siapa yg suka overthinking",
              "Spill orang yang menurut lo caper banget",
              "Spill makanan favorit",
              "Spill minuman favorit",
              "Spill yang sering typo",
              "Spill film favorit lu",
              "Spill hal paling memalukan semasa hidupmu",
              "Spill yg sering toxic",
              "Spill momen yang paling gabisa dilupain",
              "Spill kelakuan terusil lu di rumah"
             ]
